import Head from "next/head";
import UrlInput from "~/components/UrlInput";

export default function Home() {
  return (
    <>
      <Head>
        <title>Meet.io</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-screen flex-col items-center justify-center gap-24">
        <h1 className="text-4xl font-bold">Welcome to Meet.io</h1>
        <div className="w-1/2">
          <UrlInput labelText="Insert the room url" />
        </div>
      </main>

      <footer></footer>
    </>
  );
}
