import Head from "next/head";

export default function room() {
  return (
    <>
      <Head>
        <title>Room</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </>
  );
}
